export interface Database {
  public: {
    Tables: {
      users: {
        Row: {
          id: string;
          email: string;
          full_name: string;
          phone: string | null;
          avatar_url: string | null;
          bio: string | null;
          date_of_birth: string | null;
          gender: string | null;
          verification_status: 'pending' | 'approved' | 'rejected' | 'expired';
          is_verified: boolean;
          total_earnings: number;
          total_spent: number;
          rating_average: number;
          rating_count: number;
          last_seen_at: string;
          is_online: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          email: string;
          full_name: string;
          phone?: string | null;
          avatar_url?: string | null;
          bio?: string | null;
          date_of_birth?: string | null;
          gender?: string | null;
          verification_status?: 'pending' | 'approved' | 'rejected' | 'expired';
          is_verified?: boolean;
          total_earnings?: number;
          total_spent?: number;
          rating_average?: number;
          rating_count?: number;
          last_seen_at?: string;
          is_online?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          email?: string;
          full_name?: string;
          phone?: string | null;
          avatar_url?: string | null;
          bio?: string | null;
          date_of_birth?: string | null;
          gender?: string | null;
          verification_status?: 'pending' | 'approved' | 'rejected' | 'expired';
          is_verified?: boolean;
          total_earnings?: number;
          total_spent?: number;
          rating_average?: number;
          rating_count?: number;
          last_seen_at?: string;
          is_online?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      categories: {
        Row: {
          id: string;
          name: string;
          description: string | null;
          icon: string | null;
          color: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          description?: string | null;
          icon?: string | null;
          color?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          description?: string | null;
          icon?: string | null;
          color?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      items: {
        Row: {
          id: string;
          title: string;
          description: string;
          price_per_day: number;
          category_id: string;
          user_id: string;
          images: string[];
          size: string | null;
          brand: string | null;
          condition: string;
          location: string | null;
          is_available: boolean;
          deposit_amount: number;
          min_rental_days: number;
          max_rental_days: number;
          pickup_address_id: string | null;
          delivery_available: boolean;
          delivery_fee: number;
          view_count: number;
          total_bookings: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          title: string;
          description: string;
          price_per_day: number;
          category_id: string;
          user_id: string;
          images?: string[];
          size?: string | null;
          brand?: string | null;
          condition: string;
          location?: string | null;
          is_available?: boolean;
          deposit_amount?: number;
          min_rental_days?: number;
          max_rental_days?: number;
          pickup_address_id?: string | null;
          delivery_available?: boolean;
          delivery_fee?: number;
          view_count?: number;
          total_bookings?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          title?: string;
          description?: string;
          price_per_day?: number;
          category_id?: string;
          user_id?: string;
          images?: string[];
          size?: string | null;
          brand?: string | null;
          condition?: string;
          location?: string | null;
          is_available?: boolean;
          deposit_amount?: number;
          min_rental_days?: number;
          max_rental_days?: number;
          pickup_address_id?: string | null;
          delivery_available?: boolean;
          delivery_fee?: number;
          view_count?: number;
          total_bookings?: number;
          created_at?: string;
          updated_at?: string;
        };
      };
      bookings: {
        Row: {
          id: string;
          item_id: string;
          renter_id: string;
          owner_id: string;
          start_date: string;
          end_date: string;
          total_price: number;
          status: 'pending' | 'confirmed' | 'active' | 'completed' | 'cancelled';
          deposit_amount: number;
          delivery_address_id: string | null;
          pickup_address_id: string | null;
          delivery_fee: number;
          notes: string | null;
          canceled_at: string | null;
          canceled_by: string | null;
          cancellation_reason: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          item_id: string;
          renter_id: string;
          owner_id: string;
          start_date: string;
          end_date: string;
          total_price: number;
          status?: 'pending' | 'confirmed' | 'active' | 'completed' | 'cancelled';
          deposit_amount?: number;
          delivery_address_id?: string | null;
          pickup_address_id?: string | null;
          delivery_fee?: number;
          notes?: string | null;
          canceled_at?: string | null;
          canceled_by?: string | null;
          cancellation_reason?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          item_id?: string;
          renter_id?: string;
          owner_id?: string;
          start_date?: string;
          end_date?: string;
          total_price?: number;
          status?: 'pending' | 'confirmed' | 'active' | 'completed' | 'cancelled';
          deposit_amount?: number;
          delivery_address_id?: string | null;
          pickup_address_id?: string | null;
          delivery_fee?: number;
          notes?: string | null;
          canceled_at?: string | null;
          canceled_by?: string | null;
          cancellation_reason?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      reviews: {
        Row: {
          id: string;
          booking_id: string;
          reviewer_id: string;
          reviewee_id: string;
          rating: number;
          comment: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          booking_id: string;
          reviewer_id: string;
          reviewee_id: string;
          rating: number;
          comment?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          booking_id?: string;
          reviewer_id?: string;
          reviewee_id?: string;
          rating?: number;
          comment?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      favorites: {
        Row: {
          id: string;
          user_id: string;
          item_id: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          item_id: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          item_id?: string;
          created_at?: string;
        };
      };
      conversations: {
        Row: {
          id: string;
          participant1_id: string;
          participant2_id: string;
          item_id: string;
          last_message_id: string | null;
          last_message_at: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          participant1_id: string;
          participant2_id: string;
          item_id: string;
          last_message_id?: string | null;
          last_message_at?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          participant1_id?: string;
          participant2_id?: string;
          item_id?: string;
          last_message_id?: string | null;
          last_message_at?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
      messages: {
        Row: {
          id: string;
          conversation_id: string;
          sender_id: string;
          content: string;
          message_type: string;
          attachment_url: string | null;
          status: 'sent' | 'delivered' | 'read';
          read_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          conversation_id: string;
          sender_id: string;
          content: string;
          message_type?: string;
          attachment_url?: string | null;
          status?: 'sent' | 'delivered' | 'read';
          read_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          conversation_id?: string;
          sender_id?: string;
          content?: string;
          message_type?: string;
          attachment_url?: string | null;
          status?: 'sent' | 'delivered' | 'read';
          read_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      addresses: {
        Row: {
          id: string;
          user_id: string;
          label: string;
          address_line1: string;
          address_line2: string | null;
          city: string;
          state: string;
          zip_code: string;
          country: string;
          latitude: number | null;
          longitude: number | null;
          is_default: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          label: string;
          address_line1: string;
          address_line2?: string | null;
          city: string;
          state: string;
          zip_code: string;
          country?: string;
          latitude?: number | null;
          longitude?: number | null;
          is_default?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          label?: string;
          address_line1?: string;
          address_line2?: string | null;
          city?: string;
          state?: string;
          zip_code?: string;
          country?: string;
          latitude?: number | null;
          longitude?: number | null;
          is_default?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      payment_methods: {
        Row: {
          id: string;
          user_id: string;
          type: 'credit_card' | 'debit_card' | 'paypal' | 'bank_transfer';
          provider: string | null;
          external_id: string | null;
          last_four: string | null;
          card_brand: string | null;
          expiry_month: number | null;
          expiry_year: number | null;
          holder_name: string | null;
          billing_address_id: string | null;
          is_default: boolean;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          type: 'credit_card' | 'debit_card' | 'paypal' | 'bank_transfer';
          provider?: string | null;
          external_id?: string | null;
          last_four?: string | null;
          card_brand?: string | null;
          expiry_month?: number | null;
          expiry_year?: number | null;
          holder_name?: string | null;
          billing_address_id?: string | null;
          is_default?: boolean;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          type?: 'credit_card' | 'debit_card' | 'paypal' | 'bank_transfer';
          provider?: string | null;
          external_id?: string | null;
          last_four?: string | null;
          card_brand?: string | null;
          expiry_month?: number | null;
          expiry_year?: number | null;
          holder_name?: string | null;
          billing_address_id?: string | null;
          is_default?: boolean;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      payout_methods: {
        Row: {
          id: string;
          user_id: string;
          type: 'bank_account' | 'paypal' | 'stripe';
          provider: string | null;
          external_id: string | null;
          account_holder_name: string | null;
          account_number_last_four: string | null;
          routing_number_last_four: string | null;
          account_type: string | null;
          bank_name: string | null;
          paypal_email: string | null;
          is_default: boolean;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          type: 'bank_account' | 'paypal' | 'stripe';
          provider?: string | null;
          external_id?: string | null;
          account_holder_name?: string | null;
          account_number_last_four?: string | null;
          routing_number_last_four?: string | null;
          account_type?: string | null;
          bank_name?: string | null;
          paypal_email?: string | null;
          is_default?: boolean;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          type?: 'bank_account' | 'paypal' | 'stripe';
          provider?: string | null;
          external_id?: string | null;
          account_holder_name?: string | null;
          account_number_last_four?: string | null;
          routing_number_last_four?: string | null;
          account_type?: string | null;
          bank_name?: string | null;
          paypal_email?: string | null;
          is_default?: boolean;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      transactions: {
        Row: {
          id: string;
          booking_id: string;
          payer_id: string | null;
          payee_id: string | null;
          type: 'rental_payment' | 'rental_payout' | 'deposit' | 'refund' | 'fee';
          amount: number;
          fee_amount: number;
          net_amount: number;
          currency: string;
          payment_method_id: string | null;
          payout_method_id: string | null;
          external_transaction_id: string | null;
          status: string;
          description: string | null;
          processed_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          booking_id: string;
          payer_id?: string | null;
          payee_id?: string | null;
          type: 'rental_payment' | 'rental_payout' | 'deposit' | 'refund' | 'fee';
          amount: number;
          fee_amount?: number;
          net_amount: number;
          currency?: string;
          payment_method_id?: string | null;
          payout_method_id?: string | null;
          external_transaction_id?: string | null;
          status?: string;
          description?: string | null;
          processed_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          booking_id?: string;
          payer_id?: string | null;
          payee_id?: string | null;
          type?: 'rental_payment' | 'rental_payout' | 'deposit' | 'refund' | 'fee';
          amount?: number;
          fee_amount?: number;
          net_amount?: number;
          currency?: string;
          payment_method_id?: string | null;
          payout_method_id?: string | null;
          external_transaction_id?: string | null;
          status?: string;
          description?: string | null;
          processed_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      verification_documents: {
        Row: {
          id: string;
          user_id: string;
          document_type: string;
          document_url: string;
          status: 'pending' | 'approved' | 'rejected' | 'expired';
          submitted_at: string;
          reviewed_at: string | null;
          reviewer_notes: string | null;
          expiry_date: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          document_type: string;
          document_url: string;
          status?: 'pending' | 'approved' | 'rejected' | 'expired';
          submitted_at?: string;
          reviewed_at?: string | null;
          reviewer_notes?: string | null;
          expiry_date?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          document_type?: string;
          document_url?: string;
          status?: 'pending' | 'approved' | 'rejected' | 'expired';
          submitted_at?: string;
          reviewed_at?: string | null;
          reviewer_notes?: string | null;
          expiry_date?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      notifications: {
        Row: {
          id: string;
          user_id: string;
          title: string;
          message: string;
          type: string;
          related_id: string | null;
          action_url: string | null;
          is_read: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          title: string;
          message: string;
          type: string;
          related_id?: string | null;
          action_url?: string | null;
          is_read?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          title?: string;
          message?: string;
          type?: string;
          related_id?: string | null;
          action_url?: string | null;
          is_read?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      [_ in never]: never;
    };
    Enums: {
      [_ in never]: never;
    };
    CompositeTypes: {
      [_ in never]: never;
    };
  };
}
